### ISSUE TITLE
Reload/alias

### ISSUE THREAD

**Issue by Twister1one** [syldium/Thimble#1]
Salut, le plugin est top et sans bug pour le moment.
Je popose un **/th reload**
Je propose également un genre d'alias de **/th**.
Qu'on puisse le configurer. On peut le faire dans **command.yml**, mais je pense que ça pourrais être **pratique** que ce soit implémenté.
Merci pour avoir développer ce plugin ! C'est top :)

**Comment by syldium** [comment]
Hey,
Merci du retour et pour ces suggestions. La commande `reload` et la gestion des alias directement dans le fichier de configuration ont été implémentées. Ces fonctionnalités seront disponibles dans la prochaine version.

**Comment by Twister1one** [comment]
C'est top, merci ! 👯
