### ISSUE TITLE
Message.yml ?

### ISSUE THREAD

**Issue by Twister1one** [syldium/Thimble#2]
Bonjour :)

J'ai quelques idées d'implémentation et des bugs à te faire parvenir^^

- Ce serais cool d'avoir un message.yml pour éditer facilement les messages.
- Pourvoir stopper le timer avant le lancement d'une partie (/th timer pause) par exemple.
- Pouvoir exécuter une commande pour le gagnant ? (minecraft:give, /function, /eco give etc..)

Un bug lors de la victoire. Le dernier éliminé, gagne systématiquement.
![image](https://user-images.githubusercontent.com/25822504/110821979-e4c5c580-8290-11eb-9d08-42d6e6063d9f.png)
Voici le screen ci dessus.

Bonne journée :)

**Comment by syldium** [comment]
Bonsoir,

L'édition des messages est déjà supportée. Le fonctionnement est le même que celui d'EssentialsX :
Exemple pour modifier le préfixe : créer le fichier *plugins/Thimble/messages_fr.properties* (la partie après l'underscore dépend de la langue choisie) et y insérer :
```
prefix=<gray>[<yellow>DéÀCoudre</yellow>]</gray>
```
Toutes les clefs de messages sont disponibles ici : https://github.com/syldium/Thimble/blob/main/common/src/main/resources/messages_fr.properties
Ils utilisent la syntaxe MiniMessage pour le formatage, commune à certains autres plugins : https://docs.adventure.kyori.net/minimessage.html#format

En mode solo, c'est le dernier joueur en vie qui gagne, après je ne sais pas s'il y a des règles établies sur le sujet. En mode "concurrent", c'est le joueur avec le plus de points à la fin.

Je remarque sur le screen une petite erreur de traduction, *times* devrait être remplacé par *jumps*. :smile:

**Comment by syldium** [comment]
Update sur le message du screen, après un autre report, il y a bien un problème où lorsqu'il reste deux joueurs, celui qui échoue gagne. Fix à venir

**Comment by Twister1one** [comment]
D'accord pour les messages, je vais m'y atteler dans ce cas. ;) Ne serait-ce pas mieux de généré le message.yml par défaut avec toutes les clefs ? (je persiste :'))

Je suis en mode solo pour le DAC, je testerais par curiosité le mode concurrent aussi ^^
D'acc pour le fix.
