### ISSUE TITLE
Perte de stuff

### ISSUE THREAD

**Issue by Twister1one** [syldium/Thimble#3]
Salut :)

Un joueur a perdu son stuff quand il a déco après avoir rejoint un DAC et quitté.
A chaque déco/reco il le perd.
Pour réglé le soucis il a join le dac, puis quitter, et ensuite c'était corrigé.
En faisant la même manipulation qui lui a provoqué le bug :o étrange ^^

Je suis en 1.17.1

**Comment by syldium** [comment]
Hey,

Quelques détails manquent pour pouvoir reproduire le bug :
- Était-ce une partie à 1, 2, 3 ou plus joueurs ?
- À quelle phase de la partie le joueur a-t-il quitté ?
- Est-ce que c'était toujours la même phase de jeu à sa reconnexion ?

**Comment by Twister1one** [comment]
Hey ^^
La partie n'avais pas commencé car il n'y avait pas assez de joueurs.
Le joueur l'as quitter avant qu'elle ne démarre pour cause de manque de joueur.

C'est tout ce que j'ai comme info :/
