### ISSUE TITLE
Erreur console

### ISSUE THREAD

**Issue by Spinogl** [syldium/Thimble#6]
J'ai cette erreur console parfois lorsque j'utilise le plugin Thimble en version 1.8.8 paperspigot (version 1.5.1 de Thimble)

https://pastebin.com/LGt5pHxJ

**Comment by syldium** [comment]
Merci du rapport, l'exception est désormais corrigée avec la version 1.5.2 du plugin.

**Comment by syldium** [comment]
La version est disponible sur [GitHub](https://github.com/syldium/Thimble/releases) et sur [SpigotMC](https://www.spigotmc.org/resources/thimble.88191/).

**Comment by Spinogl** [comment]
Merci ! Je ne voyais pas la maj sur Spigotmc
